// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1.0
 */

package openapi




type CreateGitHubSourceArtifact struct {

	CommitId string `json:"commit_id"`
}

// AssertCreateGitHubSourceArtifactRequired checks if the required fields are not zero-ed
func AssertCreateGitHubSourceArtifactRequired(obj CreateGitHubSourceArtifact) error {
	elements := map[string]interface{}{
		"commit_id": obj.CommitId,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertCreateGitHubSourceArtifactConstraints checks if the values respects the defined constraints
func AssertCreateGitHubSourceArtifactConstraints(obj CreateGitHubSourceArtifact) error {
	return nil
}
