// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1.0
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// ArtifactsAPIService is a service that implements the logic for the ArtifactsAPIServicer
// This service should implement the business logic for every endpoint for the ArtifactsAPI API.
// Include any external packages or services that will be required by this service.
type ArtifactsAPIService struct {
}

// NewArtifactsAPIService creates a default api service
func NewArtifactsAPIService() *ArtifactsAPIService {
	return &ArtifactsAPIService{}
}

// ArtifactsArtifactIdGet - 
func (s *ArtifactsAPIService) ArtifactsArtifactIdGet(ctx context.Context, artifactId string) (ImplResponse, error) {
	// TODO - update ArtifactsArtifactIdGet with the required logic for this service method.
	// Add api_artifacts_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, Artifact{}) or use other options such as http.Ok ...
	// return Response(200, Artifact{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ArtifactsArtifactIdGet method not implemented")
}

// ArtifactsArtifactIdDeploymentsGet - 
func (s *ArtifactsAPIService) ArtifactsArtifactIdDeploymentsGet(ctx context.Context, artifactId string) (ImplResponse, error) {
	// TODO - update ArtifactsArtifactIdDeploymentsGet with the required logic for this service method.
	// Add api_artifacts_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, ArtifactDeploymentList{}) or use other options such as http.Ok ...
	// return Response(200, ArtifactDeploymentList{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ArtifactsArtifactIdDeploymentsGet method not implemented")
}

// ArtifactsArtifactIdDeploymentFilesGet - 
func (s *ArtifactsAPIService) ArtifactsArtifactIdDeploymentFilesGet(ctx context.Context, artifactId string) (ImplResponse, error) {
	// TODO - update ArtifactsArtifactIdDeploymentFilesGet with the required logic for this service method.
	// Add api_artifacts_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, ArtifactDeploymentFiles{}) or use other options such as http.Ok ...
	// return Response(200, ArtifactDeploymentFiles{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ArtifactsArtifactIdDeploymentFilesGet method not implemented")
}

// GroupsGroupIdArtifactsGet - 
func (s *ArtifactsAPIService) GroupsGroupIdArtifactsGet(ctx context.Context, groupId string, onlyStaged bool) (ImplResponse, error) {
	// TODO - update GroupsGroupIdArtifactsGet with the required logic for this service method.
	// Add api_artifacts_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, GroupArtifactList{}) or use other options such as http.Ok ...
	// return Response(200, GroupArtifactList{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GroupsGroupIdArtifactsGet method not implemented")
}

// SourcesRegistryRegistrySourceIdArtifactsPost - 
func (s *ArtifactsAPIService) SourcesRegistryRegistrySourceIdArtifactsPost(ctx context.Context, registrySourceId string, createRegistrySourceArtifact CreateRegistrySourceArtifact) (ImplResponse, error) {
	// TODO - update SourcesRegistryRegistrySourceIdArtifactsPost with the required logic for this service method.
	// Add api_artifacts_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, Artifact{}) or use other options such as http.Ok ...
	// return Response(200, Artifact{}), nil

	// TODO: Uncomment the next line to return response Response(409, Error{}) or use other options such as http.Ok ...
	// return Response(409, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("SourcesRegistryRegistrySourceIdArtifactsPost method not implemented")
}

// SourcesGithubGithubSourceIdArtifactsPost - 
func (s *ArtifactsAPIService) SourcesGithubGithubSourceIdArtifactsPost(ctx context.Context, githubSourceId string, createGitHubSourceArtifact CreateGitHubSourceArtifact) (ImplResponse, error) {
	// TODO - update SourcesGithubGithubSourceIdArtifactsPost with the required logic for this service method.
	// Add api_artifacts_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	// return Response(200, nil),nil

	// TODO: Uncomment the next line to return response Response(409, Error{}) or use other options such as http.Ok ...
	// return Response(409, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("SourcesGithubGithubSourceIdArtifactsPost method not implemented")
}
