// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1.0
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// GenericErrorsAPIService is a service that implements the logic for the GenericErrorsAPIServicer
// This service should implement the business logic for every endpoint for the GenericErrorsAPI API.
// Include any external packages or services that will be required by this service.
type GenericErrorsAPIService struct {
}

// NewGenericErrorsAPIService creates a default api service
func NewGenericErrorsAPIService() *GenericErrorsAPIService {
	return &GenericErrorsAPIService{}
}

// ExampleErrors400Get - 
func (s *GenericErrorsAPIService) ExampleErrors400Get(ctx context.Context) (ImplResponse, error) {
	// TODO - update ExampleErrors400Get with the required logic for this service method.
	// Add api_generic_errors_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(400, Error4{}) or use other options such as http.Ok ...
	// return Response(400, Error4{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ExampleErrors400Get method not implemented")
}

// ExampleErrors401Get - 
func (s *GenericErrorsAPIService) ExampleErrors401Get(ctx context.Context) (ImplResponse, error) {
	// TODO - update ExampleErrors401Get with the required logic for this service method.
	// Add api_generic_errors_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(401, Error{}) or use other options such as http.Ok ...
	// return Response(401, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ExampleErrors401Get method not implemented")
}

// ExampleErrors403Get - 
func (s *GenericErrorsAPIService) ExampleErrors403Get(ctx context.Context) (ImplResponse, error) {
	// TODO - update ExampleErrors403Get with the required logic for this service method.
	// Add api_generic_errors_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(403, Error1{}) or use other options such as http.Ok ...
	// return Response(403, Error1{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ExampleErrors403Get method not implemented")
}

// ExampleErrors404Get - 
func (s *GenericErrorsAPIService) ExampleErrors404Get(ctx context.Context) (ImplResponse, error) {
	// TODO - update ExampleErrors404Get with the required logic for this service method.
	// Add api_generic_errors_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(404, Error2{}) or use other options such as http.Ok ...
	// return Response(404, Error2{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ExampleErrors404Get method not implemented")
}
