// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1.0
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// RepositoriesAPIService is a service that implements the logic for the RepositoriesAPIServicer
// This service should implement the business logic for every endpoint for the RepositoriesAPI API.
// Include any external packages or services that will be required by this service.
type RepositoriesAPIService struct {
}

// NewRepositoriesAPIService creates a default api service
func NewRepositoriesAPIService() *RepositoriesAPIService {
	return &RepositoriesAPIService{}
}

// IntegrationsDockerhubDockerhubIntegrationIdRepositoriesExternalGet - 
func (s *RepositoriesAPIService) IntegrationsDockerhubDockerhubIntegrationIdRepositoriesExternalGet(ctx context.Context, dockerhubIntegrationId string) (ImplResponse, error) {
	// TODO - update IntegrationsDockerhubDockerhubIntegrationIdRepositoriesExternalGet with the required logic for this service method.
	// Add api_repositories_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, ExternalRepositoryList{}) or use other options such as http.Ok ...
	// return Response(200, ExternalRepositoryList{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("IntegrationsDockerhubDockerhubIntegrationIdRepositoriesExternalGet method not implemented")
}

// IntegrationsGarGarIntegrationIdRepositoriesExternalGet - 
func (s *RepositoriesAPIService) IntegrationsGarGarIntegrationIdRepositoriesExternalGet(ctx context.Context, garIntegrationId string) (ImplResponse, error) {
	// TODO - update IntegrationsGarGarIntegrationIdRepositoriesExternalGet with the required logic for this service method.
	// Add api_repositories_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, ExternalRepositoryList{}) or use other options such as http.Ok ...
	// return Response(200, ExternalRepositoryList{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("IntegrationsGarGarIntegrationIdRepositoriesExternalGet method not implemented")
}

// WorkspacesWorkspaceIdRepositoriesExternalGet - 
func (s *RepositoriesAPIService) WorkspacesWorkspaceIdRepositoriesExternalGet(ctx context.Context, workspaceId string) (ImplResponse, error) {
	// TODO - update WorkspacesWorkspaceIdRepositoriesExternalGet with the required logic for this service method.
	// Add api_repositories_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, ExternalRepositoryList{}) or use other options such as http.Ok ...
	// return Response(200, ExternalRepositoryList{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("WorkspacesWorkspaceIdRepositoriesExternalGet method not implemented")
}

// RepositoriesRepositoryIdGet - 
func (s *RepositoriesAPIService) RepositoriesRepositoryIdGet(ctx context.Context, repositoryId string) (ImplResponse, error) {
	// TODO - update RepositoriesRepositoryIdGet with the required logic for this service method.
	// Add api_repositories_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, Repository{}) or use other options such as http.Ok ...
	// return Response(200, Repository{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("RepositoriesRepositoryIdGet method not implemented")
}

// RepositoriesRepositoryIdImagesExternalGet - 
func (s *RepositoriesAPIService) RepositoriesRepositoryIdImagesExternalGet(ctx context.Context, repositoryId string) (ImplResponse, error) {
	// TODO - update RepositoriesRepositoryIdImagesExternalGet with the required logic for this service method.
	// Add api_repositories_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, ExternalImageList{}) or use other options such as http.Ok ...
	// return Response(200, ExternalImageList{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("RepositoriesRepositoryIdImagesExternalGet method not implemented")
}
