// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1.0
 */

package openapi




type RepositoryNotFoundParams struct {

	RegistryType string `json:"registry_type"`

	RegistryUrl string `json:"registry_url"`

	RepositoryName string `json:"repository_name"`

	Uri string `json:"uri"`
}

// AssertRepositoryNotFoundParamsRequired checks if the required fields are not zero-ed
func AssertRepositoryNotFoundParamsRequired(obj RepositoryNotFoundParams) error {
	elements := map[string]interface{}{
		"registry_type": obj.RegistryType,
		"registry_url": obj.RegistryUrl,
		"repository_name": obj.RepositoryName,
		"uri": obj.Uri,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRepositoryNotFoundParamsConstraints checks if the values respects the defined constraints
func AssertRepositoryNotFoundParamsConstraints(obj RepositoryNotFoundParams) error {
	return nil
}
