// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1.0
 */

package openapi




type RepositoryList struct {

	Object string `json:"object,omitempty"`

	Data []Repository `json:"data,omitempty"`
}

// AssertRepositoryListRequired checks if the required fields are not zero-ed
func AssertRepositoryListRequired(obj RepositoryList) error {
	for _, el := range obj.Data {
		if err := AssertRepositoryRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRepositoryListConstraints checks if the values respects the defined constraints
func AssertRepositoryListConstraints(obj RepositoryList) error {
	for _, el := range obj.Data {
		if err := AssertRepositoryConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
