openapi: 3.0.3
info:
  title: Artifacts 
  version: 0.1.0
paths:
  /internal/v1/workspaces/{workspace_id}/artifact:
    post:
      tags:
        - Artifacts 
      parameters:
        - name: workspace_id 
          in: path
          required: true
          description: The unique identifier of the workspace
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                registry_source_name:
                  type: string
                  example: "Ad Display V2.2.1"
                  description: The name of the registry source.
                compose_file:
                  type: string
                  example: "name: miru\nservices:\n  redis:\n  image: redis:latest\n  restart: always"
                  description: The compose file for the registry source.
                aarch64:
                  type: boolean
                  example: true
                  description: Whether the registry source is aarch64.
                x86_64:
                  type: boolean
                  example: false 
                  description: Whether the registry source is x86_64.
                
      responses:
        '200':
          description: Successfully created the registry source for the workspace.
          content:
            application/json:
              schema:
                type: object
                properties:
                  registry_source_id:
                    type: string
                    example: "reg_src_1234"
                    description: The unique identifier of the device. 
  /internal/v1/sources/artifacts/{artifact_id}:
    get:
      tags:
        - Artifacts
      parameters:
        - name: artifact_id 
          in: path
          required: true
          description: The unique identifier of the artifact.
          schema:
            type: string
      responses:
        '200':
          description: Successfully retrieved the artifact.
          content:
            application/json:
              schema:
                type: object
                properties:
                  artifact_id:
                    type: string
                    example: "art_1234"
    patch:
      tags:
        - Artifacts
      parameters:
        - name: registry_id 
          in: path
          required: true
          description: The unique identifier of the registry source.
          schema:
            type: string
      responses:
        '200':
          description: Successfully retrieved the registry source.
          content:
            application/json:
              schema:
                type: object
                properties:
                  registry_source_id:
                    type: string
                    example: "reg_src_1234"


# group artifacts: /artifacts, /artifacts/staged, /artifacts/:artifact_id