/*
Miru API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RepositoryWithIsExtra type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RepositoryWithIsExtra{}

// RepositoryWithIsExtra struct for RepositoryWithIsExtra
type RepositoryWithIsExtra struct {
	Object string `json:"object"`
	RegistryUrl string `json:"registry_url"`
	Name string `json:"name"`
	Uri string `json:"uri"`
	Id string `json:"id"`
	IsExtra bool `json:"is_extra"`
}

type _RepositoryWithIsExtra RepositoryWithIsExtra

// NewRepositoryWithIsExtra instantiates a new RepositoryWithIsExtra object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRepositoryWithIsExtra(object string, registryUrl string, name string, uri string, id string, isExtra bool) *RepositoryWithIsExtra {
	this := RepositoryWithIsExtra{}
	this.Object = object
	this.RegistryUrl = registryUrl
	this.Name = name
	this.Uri = uri
	this.Id = id
	this.IsExtra = isExtra
	return &this
}

// NewRepositoryWithIsExtraWithDefaults instantiates a new RepositoryWithIsExtra object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRepositoryWithIsExtraWithDefaults() *RepositoryWithIsExtra {
	this := RepositoryWithIsExtra{}
	return &this
}

// GetObject returns the Object field value
func (o *RepositoryWithIsExtra) GetObject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Object
}

// GetObjectOk returns a tuple with the Object field value
// and a boolean to check if the value has been set.
func (o *RepositoryWithIsExtra) GetObjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Object, true
}

// SetObject sets field value
func (o *RepositoryWithIsExtra) SetObject(v string) {
	o.Object = v
}

// GetRegistryUrl returns the RegistryUrl field value
func (o *RepositoryWithIsExtra) GetRegistryUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RegistryUrl
}

// GetRegistryUrlOk returns a tuple with the RegistryUrl field value
// and a boolean to check if the value has been set.
func (o *RepositoryWithIsExtra) GetRegistryUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RegistryUrl, true
}

// SetRegistryUrl sets field value
func (o *RepositoryWithIsExtra) SetRegistryUrl(v string) {
	o.RegistryUrl = v
}

// GetName returns the Name field value
func (o *RepositoryWithIsExtra) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *RepositoryWithIsExtra) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *RepositoryWithIsExtra) SetName(v string) {
	o.Name = v
}

// GetUri returns the Uri field value
func (o *RepositoryWithIsExtra) GetUri() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uri
}

// GetUriOk returns a tuple with the Uri field value
// and a boolean to check if the value has been set.
func (o *RepositoryWithIsExtra) GetUriOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uri, true
}

// SetUri sets field value
func (o *RepositoryWithIsExtra) SetUri(v string) {
	o.Uri = v
}

// GetId returns the Id field value
func (o *RepositoryWithIsExtra) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *RepositoryWithIsExtra) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *RepositoryWithIsExtra) SetId(v string) {
	o.Id = v
}

// GetIsExtra returns the IsExtra field value
func (o *RepositoryWithIsExtra) GetIsExtra() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsExtra
}

// GetIsExtraOk returns a tuple with the IsExtra field value
// and a boolean to check if the value has been set.
func (o *RepositoryWithIsExtra) GetIsExtraOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsExtra, true
}

// SetIsExtra sets field value
func (o *RepositoryWithIsExtra) SetIsExtra(v bool) {
	o.IsExtra = v
}

func (o RepositoryWithIsExtra) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RepositoryWithIsExtra) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["object"] = o.Object
	toSerialize["registry_url"] = o.RegistryUrl
	toSerialize["name"] = o.Name
	toSerialize["uri"] = o.Uri
	toSerialize["id"] = o.Id
	toSerialize["is_extra"] = o.IsExtra
	return toSerialize, nil
}

func (o *RepositoryWithIsExtra) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"object",
		"registry_url",
		"name",
		"uri",
		"id",
		"is_extra",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRepositoryWithIsExtra := _RepositoryWithIsExtra{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRepositoryWithIsExtra)

	if err != nil {
		return err
	}

	*o = RepositoryWithIsExtra(varRepositoryWithIsExtra)

	return err
}

type NullableRepositoryWithIsExtra struct {
	value *RepositoryWithIsExtra
	isSet bool
}

func (v NullableRepositoryWithIsExtra) Get() *RepositoryWithIsExtra {
	return v.value
}

func (v *NullableRepositoryWithIsExtra) Set(val *RepositoryWithIsExtra) {
	v.value = val
	v.isSet = true
}

func (v NullableRepositoryWithIsExtra) IsSet() bool {
	return v.isSet
}

func (v *NullableRepositoryWithIsExtra) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRepositoryWithIsExtra(val *RepositoryWithIsExtra) *NullableRepositoryWithIsExtra {
	return &NullableRepositoryWithIsExtra{value: val, isSet: true}
}

func (v NullableRepositoryWithIsExtra) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRepositoryWithIsExtra) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


