/*
Miru API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the ArtifactBase type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ArtifactBase{}

// ArtifactBase struct for ArtifactBase
type ArtifactBase struct {
	Object string `json:"object"`
	Id string `json:"id"`
	Status ArtifactStatus `json:"status"`
	Digest string `json:"digest"`
	Aarch64 bool `json:"aarch64"`
	X8664 bool `json:"x86_64"`
	CreatedAt time.Time `json:"created_at"`
	ReadyAt NullableTime `json:"ready_at"`
	FailedAt NullableTime `json:"failed_at"`
	CreatedBy *User `json:"created_by,omitempty"`
	SourceId string `json:"source_id"`
	SourceType string `json:"source_type"`
	RegistrySource RegistrySource `json:"registry_source"`
	GithubSource GitHubSource `json:"github_source"`
	GithubSourceData GitHubSourceData `json:"github_source_data"`
}

type _ArtifactBase ArtifactBase

// NewArtifactBase instantiates a new ArtifactBase object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewArtifactBase(object string, id string, status ArtifactStatus, digest string, aarch64 bool, x8664 bool, createdAt time.Time, readyAt NullableTime, failedAt NullableTime, sourceId string, sourceType string, registrySource RegistrySource, githubSource GitHubSource, githubSourceData GitHubSourceData) *ArtifactBase {
	this := ArtifactBase{}
	this.Object = object
	this.Id = id
	this.Status = status
	this.Digest = digest
	this.Aarch64 = aarch64
	this.X8664 = x8664
	this.CreatedAt = createdAt
	this.ReadyAt = readyAt
	this.FailedAt = failedAt
	this.SourceId = sourceId
	this.SourceType = sourceType
	this.RegistrySource = registrySource
	this.GithubSource = githubSource
	this.GithubSourceData = githubSourceData
	return &this
}

// NewArtifactBaseWithDefaults instantiates a new ArtifactBase object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewArtifactBaseWithDefaults() *ArtifactBase {
	this := ArtifactBase{}
	return &this
}

// GetObject returns the Object field value
func (o *ArtifactBase) GetObject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Object
}

// GetObjectOk returns a tuple with the Object field value
// and a boolean to check if the value has been set.
func (o *ArtifactBase) GetObjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Object, true
}

// SetObject sets field value
func (o *ArtifactBase) SetObject(v string) {
	o.Object = v
}

// GetId returns the Id field value
func (o *ArtifactBase) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ArtifactBase) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ArtifactBase) SetId(v string) {
	o.Id = v
}

// GetStatus returns the Status field value
func (o *ArtifactBase) GetStatus() ArtifactStatus {
	if o == nil {
		var ret ArtifactStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ArtifactBase) GetStatusOk() (*ArtifactStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ArtifactBase) SetStatus(v ArtifactStatus) {
	o.Status = v
}

// GetDigest returns the Digest field value
func (o *ArtifactBase) GetDigest() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Digest
}

// GetDigestOk returns a tuple with the Digest field value
// and a boolean to check if the value has been set.
func (o *ArtifactBase) GetDigestOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Digest, true
}

// SetDigest sets field value
func (o *ArtifactBase) SetDigest(v string) {
	o.Digest = v
}

// GetAarch64 returns the Aarch64 field value
func (o *ArtifactBase) GetAarch64() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Aarch64
}

// GetAarch64Ok returns a tuple with the Aarch64 field value
// and a boolean to check if the value has been set.
func (o *ArtifactBase) GetAarch64Ok() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Aarch64, true
}

// SetAarch64 sets field value
func (o *ArtifactBase) SetAarch64(v bool) {
	o.Aarch64 = v
}

// GetX8664 returns the X8664 field value
func (o *ArtifactBase) GetX8664() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.X8664
}

// GetX8664Ok returns a tuple with the X8664 field value
// and a boolean to check if the value has been set.
func (o *ArtifactBase) GetX8664Ok() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.X8664, true
}

// SetX8664 sets field value
func (o *ArtifactBase) SetX8664(v bool) {
	o.X8664 = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *ArtifactBase) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *ArtifactBase) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *ArtifactBase) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetReadyAt returns the ReadyAt field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *ArtifactBase) GetReadyAt() time.Time {
	if o == nil || o.ReadyAt.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.ReadyAt.Get()
}

// GetReadyAtOk returns a tuple with the ReadyAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ArtifactBase) GetReadyAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReadyAt.Get(), o.ReadyAt.IsSet()
}

// SetReadyAt sets field value
func (o *ArtifactBase) SetReadyAt(v time.Time) {
	o.ReadyAt.Set(&v)
}

// GetFailedAt returns the FailedAt field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *ArtifactBase) GetFailedAt() time.Time {
	if o == nil || o.FailedAt.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.FailedAt.Get()
}

// GetFailedAtOk returns a tuple with the FailedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ArtifactBase) GetFailedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.FailedAt.Get(), o.FailedAt.IsSet()
}

// SetFailedAt sets field value
func (o *ArtifactBase) SetFailedAt(v time.Time) {
	o.FailedAt.Set(&v)
}

// GetCreatedBy returns the CreatedBy field value if set, zero value otherwise.
func (o *ArtifactBase) GetCreatedBy() User {
	if o == nil || IsNil(o.CreatedBy) {
		var ret User
		return ret
	}
	return *o.CreatedBy
}

// GetCreatedByOk returns a tuple with the CreatedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArtifactBase) GetCreatedByOk() (*User, bool) {
	if o == nil || IsNil(o.CreatedBy) {
		return nil, false
	}
	return o.CreatedBy, true
}

// HasCreatedBy returns a boolean if a field has been set.
func (o *ArtifactBase) HasCreatedBy() bool {
	if o != nil && !IsNil(o.CreatedBy) {
		return true
	}

	return false
}

// SetCreatedBy gets a reference to the given User and assigns it to the CreatedBy field.
func (o *ArtifactBase) SetCreatedBy(v User) {
	o.CreatedBy = &v
}

// GetSourceId returns the SourceId field value
func (o *ArtifactBase) GetSourceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceId
}

// GetSourceIdOk returns a tuple with the SourceId field value
// and a boolean to check if the value has been set.
func (o *ArtifactBase) GetSourceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceId, true
}

// SetSourceId sets field value
func (o *ArtifactBase) SetSourceId(v string) {
	o.SourceId = v
}

// GetSourceType returns the SourceType field value
func (o *ArtifactBase) GetSourceType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceType
}

// GetSourceTypeOk returns a tuple with the SourceType field value
// and a boolean to check if the value has been set.
func (o *ArtifactBase) GetSourceTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceType, true
}

// SetSourceType sets field value
func (o *ArtifactBase) SetSourceType(v string) {
	o.SourceType = v
}

// GetRegistrySource returns the RegistrySource field value
func (o *ArtifactBase) GetRegistrySource() RegistrySource {
	if o == nil {
		var ret RegistrySource
		return ret
	}

	return o.RegistrySource
}

// GetRegistrySourceOk returns a tuple with the RegistrySource field value
// and a boolean to check if the value has been set.
func (o *ArtifactBase) GetRegistrySourceOk() (*RegistrySource, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RegistrySource, true
}

// SetRegistrySource sets field value
func (o *ArtifactBase) SetRegistrySource(v RegistrySource) {
	o.RegistrySource = v
}

// GetGithubSource returns the GithubSource field value
func (o *ArtifactBase) GetGithubSource() GitHubSource {
	if o == nil {
		var ret GitHubSource
		return ret
	}

	return o.GithubSource
}

// GetGithubSourceOk returns a tuple with the GithubSource field value
// and a boolean to check if the value has been set.
func (o *ArtifactBase) GetGithubSourceOk() (*GitHubSource, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GithubSource, true
}

// SetGithubSource sets field value
func (o *ArtifactBase) SetGithubSource(v GitHubSource) {
	o.GithubSource = v
}

// GetGithubSourceData returns the GithubSourceData field value
func (o *ArtifactBase) GetGithubSourceData() GitHubSourceData {
	if o == nil {
		var ret GitHubSourceData
		return ret
	}

	return o.GithubSourceData
}

// GetGithubSourceDataOk returns a tuple with the GithubSourceData field value
// and a boolean to check if the value has been set.
func (o *ArtifactBase) GetGithubSourceDataOk() (*GitHubSourceData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GithubSourceData, true
}

// SetGithubSourceData sets field value
func (o *ArtifactBase) SetGithubSourceData(v GitHubSourceData) {
	o.GithubSourceData = v
}

func (o ArtifactBase) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ArtifactBase) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["object"] = o.Object
	toSerialize["id"] = o.Id
	toSerialize["status"] = o.Status
	toSerialize["digest"] = o.Digest
	toSerialize["aarch64"] = o.Aarch64
	toSerialize["x86_64"] = o.X8664
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["ready_at"] = o.ReadyAt.Get()
	toSerialize["failed_at"] = o.FailedAt.Get()
	if !IsNil(o.CreatedBy) {
		toSerialize["created_by"] = o.CreatedBy
	}
	toSerialize["source_id"] = o.SourceId
	toSerialize["source_type"] = o.SourceType
	toSerialize["registry_source"] = o.RegistrySource
	toSerialize["github_source"] = o.GithubSource
	toSerialize["github_source_data"] = o.GithubSourceData
	return toSerialize, nil
}

func (o *ArtifactBase) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"object",
		"id",
		"status",
		"digest",
		"aarch64",
		"x86_64",
		"created_at",
		"ready_at",
		"failed_at",
		"source_id",
		"source_type",
		"registry_source",
		"github_source",
		"github_source_data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varArtifactBase := _ArtifactBase{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varArtifactBase)

	if err != nil {
		return err
	}

	*o = ArtifactBase(varArtifactBase)

	return err
}

type NullableArtifactBase struct {
	value *ArtifactBase
	isSet bool
}

func (v NullableArtifactBase) Get() *ArtifactBase {
	return v.value
}

func (v *NullableArtifactBase) Set(val *ArtifactBase) {
	v.value = val
	v.isSet = true
}

func (v NullableArtifactBase) IsSet() bool {
	return v.isSet
}

func (v *NullableArtifactBase) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableArtifactBase(val *ArtifactBase) *NullableArtifactBase {
	return &NullableArtifactBase{value: val, isSet: true}
}

func (v NullableArtifactBase) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableArtifactBase) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


