/*
Miru API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RegistrySourceContainerRepositoryList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegistrySourceContainerRepositoryList{}

// RegistrySourceContainerRepositoryList struct for RegistrySourceContainerRepositoryList
type RegistrySourceContainerRepositoryList struct {
	Object string `json:"object"`
	Data []RegistrySourceContainerRepository `json:"data"`
}

type _RegistrySourceContainerRepositoryList RegistrySourceContainerRepositoryList

// NewRegistrySourceContainerRepositoryList instantiates a new RegistrySourceContainerRepositoryList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegistrySourceContainerRepositoryList(object string, data []RegistrySourceContainerRepository) *RegistrySourceContainerRepositoryList {
	this := RegistrySourceContainerRepositoryList{}
	this.Object = object
	this.Data = data
	return &this
}

// NewRegistrySourceContainerRepositoryListWithDefaults instantiates a new RegistrySourceContainerRepositoryList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegistrySourceContainerRepositoryListWithDefaults() *RegistrySourceContainerRepositoryList {
	this := RegistrySourceContainerRepositoryList{}
	return &this
}

// GetObject returns the Object field value
func (o *RegistrySourceContainerRepositoryList) GetObject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Object
}

// GetObjectOk returns a tuple with the Object field value
// and a boolean to check if the value has been set.
func (o *RegistrySourceContainerRepositoryList) GetObjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Object, true
}

// SetObject sets field value
func (o *RegistrySourceContainerRepositoryList) SetObject(v string) {
	o.Object = v
}

// GetData returns the Data field value
func (o *RegistrySourceContainerRepositoryList) GetData() []RegistrySourceContainerRepository {
	if o == nil {
		var ret []RegistrySourceContainerRepository
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *RegistrySourceContainerRepositoryList) GetDataOk() ([]RegistrySourceContainerRepository, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *RegistrySourceContainerRepositoryList) SetData(v []RegistrySourceContainerRepository) {
	o.Data = v
}

func (o RegistrySourceContainerRepositoryList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegistrySourceContainerRepositoryList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["object"] = o.Object
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *RegistrySourceContainerRepositoryList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"object",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRegistrySourceContainerRepositoryList := _RegistrySourceContainerRepositoryList{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRegistrySourceContainerRepositoryList)

	if err != nil {
		return err
	}

	*o = RegistrySourceContainerRepositoryList(varRegistrySourceContainerRepositoryList)

	return err
}

type NullableRegistrySourceContainerRepositoryList struct {
	value *RegistrySourceContainerRepositoryList
	isSet bool
}

func (v NullableRegistrySourceContainerRepositoryList) Get() *RegistrySourceContainerRepositoryList {
	return v.value
}

func (v *NullableRegistrySourceContainerRepositoryList) Set(val *RegistrySourceContainerRepositoryList) {
	v.value = val
	v.isSet = true
}

func (v NullableRegistrySourceContainerRepositoryList) IsSet() bool {
	return v.isSet
}

func (v *NullableRegistrySourceContainerRepositoryList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegistrySourceContainerRepositoryList(val *RegistrySourceContainerRepositoryList) *NullableRegistrySourceContainerRepositoryList {
	return &NullableRegistrySourceContainerRepositoryList{value: val, isSet: true}
}

func (v NullableRegistrySourceContainerRepositoryList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegistrySourceContainerRepositoryList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


