/*
Miru API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DeploymentLogList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeploymentLogList{}

// DeploymentLogList struct for DeploymentLogList
type DeploymentLogList struct {
	Object string `json:"object"`
	Data []DeploymentLog `json:"data"`
}

type _DeploymentLogList DeploymentLogList

// NewDeploymentLogList instantiates a new DeploymentLogList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeploymentLogList(object string, data []DeploymentLog) *DeploymentLogList {
	this := DeploymentLogList{}
	this.Object = object
	this.Data = data
	return &this
}

// NewDeploymentLogListWithDefaults instantiates a new DeploymentLogList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeploymentLogListWithDefaults() *DeploymentLogList {
	this := DeploymentLogList{}
	return &this
}

// GetObject returns the Object field value
func (o *DeploymentLogList) GetObject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Object
}

// GetObjectOk returns a tuple with the Object field value
// and a boolean to check if the value has been set.
func (o *DeploymentLogList) GetObjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Object, true
}

// SetObject sets field value
func (o *DeploymentLogList) SetObject(v string) {
	o.Object = v
}

// GetData returns the Data field value
func (o *DeploymentLogList) GetData() []DeploymentLog {
	if o == nil {
		var ret []DeploymentLog
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *DeploymentLogList) GetDataOk() ([]DeploymentLog, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *DeploymentLogList) SetData(v []DeploymentLog) {
	o.Data = v
}

func (o DeploymentLogList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeploymentLogList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["object"] = o.Object
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *DeploymentLogList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"object",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeploymentLogList := _DeploymentLogList{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeploymentLogList)

	if err != nil {
		return err
	}

	*o = DeploymentLogList(varDeploymentLogList)

	return err
}

type NullableDeploymentLogList struct {
	value *DeploymentLogList
	isSet bool
}

func (v NullableDeploymentLogList) Get() *DeploymentLogList {
	return v.value
}

func (v *NullableDeploymentLogList) Set(val *DeploymentLogList) {
	v.value = val
	v.isSet = true
}

func (v NullableDeploymentLogList) IsSet() bool {
	return v.isSet
}

func (v *NullableDeploymentLogList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeploymentLogList(val *DeploymentLogList) *NullableDeploymentLogList {
	return &NullableDeploymentLogList{value: val, isSet: true}
}

func (v NullableDeploymentLogList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeploymentLogList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


