/*
Miru API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ArtifactList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ArtifactList{}

// ArtifactList struct for ArtifactList
type ArtifactList struct {
	Object string `json:"object"`
	Data []Artifact `json:"data"`
}

type _ArtifactList ArtifactList

// NewArtifactList instantiates a new ArtifactList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewArtifactList(object string, data []Artifact) *ArtifactList {
	this := ArtifactList{}
	this.Object = object
	this.Data = data
	return &this
}

// NewArtifactListWithDefaults instantiates a new ArtifactList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewArtifactListWithDefaults() *ArtifactList {
	this := ArtifactList{}
	return &this
}

// GetObject returns the Object field value
func (o *ArtifactList) GetObject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Object
}

// GetObjectOk returns a tuple with the Object field value
// and a boolean to check if the value has been set.
func (o *ArtifactList) GetObjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Object, true
}

// SetObject sets field value
func (o *ArtifactList) SetObject(v string) {
	o.Object = v
}

// GetData returns the Data field value
func (o *ArtifactList) GetData() []Artifact {
	if o == nil {
		var ret []Artifact
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ArtifactList) GetDataOk() ([]Artifact, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *ArtifactList) SetData(v []Artifact) {
	o.Data = v
}

func (o ArtifactList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ArtifactList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["object"] = o.Object
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *ArtifactList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"object",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varArtifactList := _ArtifactList{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varArtifactList)

	if err != nil {
		return err
	}

	*o = ArtifactList(varArtifactList)

	return err
}

type NullableArtifactList struct {
	value *ArtifactList
	isSet bool
}

func (v NullableArtifactList) Get() *ArtifactList {
	return v.value
}

func (v *NullableArtifactList) Set(val *ArtifactList) {
	v.value = val
	v.isSet = true
}

func (v NullableArtifactList) IsSet() bool {
	return v.isSet
}

func (v *NullableArtifactList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableArtifactList(val *ArtifactList) *NullableArtifactList {
	return &NullableArtifactList{value: val, isSet: true}
}

func (v NullableArtifactList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableArtifactList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


