openapi: 3.0.3
info:
  title: Artifacts
  version: ""
paths:
  /artifacts/{artifact_id}:
    get:
      tags:
        - Artifacts
      security:
        - ClerkAuth: []
      parameters:
        - $ref: '../../params.yaml#/components/parameters/artifact_id'
      responses:
        '200':
          description: Successfully retrieved the artifact.
          content:
            application/json:
              schema:
                $ref: '../schemas/artifact.yaml#/components/schemas/Artifact'
  /artifacts/{artifact_id}/compose_file:
    get:
      tags:
        - Artifacts
      security:
        - ClerkAuth: []
      parameters:
        - $ref: '../../params.yaml#/components/parameters/artifact_id'
      responses:
        '200':
          description: Successfully retrieved the compose file for the artifact.
          content:
            application/json:
              schema:
                $ref: '../schemas/artifact.yaml#/components/schemas/ComposeFile'
  /sources/registries/{registry_source_id}/artifacts:
    post:
      tags:
        - Artifacts
      security:
        - ClerkAuth: []
      parameters:
        - $ref: '../../params.yaml#/components/parameters/registry_source_id'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../schemas/artifact.yaml#/components/schemas/CreateRegistrySourceArtifact'
      responses:
        '200':
          description: Successfully created the artifact.
          content:
            application/json:
              schema:
                $ref: '../schemas/artifact.yaml#/components/schemas/Artifact'
  /sources/github/{github_source_id}/artifacts:
    post:
      tags:
        - Artifacts
      security:
        - ClerkAuth: []
      parameters:
        - $ref: '../../params.yaml#/components/parameters/github_source_id'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../schemas/artifact.yaml#/components/schemas/CreateGitHubSourceArtifact'
      responses:
        '200':
          description: Successfully created the artifact.
          content:
            application/json:
              schema:
                $ref: '../schemas/artifact.yaml#/components/schemas/Artifact'
