openapi: 3.0.3
info:
  title: Container Images 
  version: ""
paths:
  /repositories/container/{container_repository_id}/images/external:
    get:
      tags:
        - Container Images
      parameters:
        - $ref: '../../params.yaml#/components/parameters/container_repository_id'
        - $ref: '../../params.yaml#/components/parameters/page_size'
      responses:
        '200':
          description: Successfully retrieved the images for the repository.
          content:
            application/json:
              schema:
                $ref: '../schemas/image.yaml#/components/schemas/ExternalContainerImageList'
