openapi: 3.0.3
info:
  title: Registry Sources 
  version: ""
paths:
  /workspaces/{workspace_id}/sources/registry:
    get:
      tags:
        - Registry Sources
      parameters:
        - $ref: '../parameters.yaml#/components/parameters/workspace_id'
      responses:
        '200':
          description: Successfully retrieved the registry sources for the workspace.
          content:
            application/json:
              schema:
                type: array 
                items:
                  $ref: '../schemas/reg-src.yaml#/components/schemas/RegistrySource'
    post:
      tags:
        - Registry Sources
      parameters:
        - name: workspace_id 
          in: path
          required: true
          description: The unique identifier of the workspace
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../schemas/reg-src.yaml#/components/schemas/CreateRegistrySource'
      responses:
        '200':
          description: Successfully created the registry source for the workspace.
          content:
            application/json:
              schema:
                type: object
                properties:
                  registry_source_id:
                    type: string
                    example: "reg_src_1234"
  /sources/registry/{registry_id}:
    get:
      tags:
        - Registry Sources
      parameters:
        - name: registry_id 
          in: path
          required: true
          description: The unique identifier of the registry source.
          schema:
            type: string
      responses:
        '200':
          description: Successfully retrieved the registry source.
          content:
            application/json:
              schema:
                $ref: '../schemas/reg-src.yaml#/components/schemas/RegistrySource'
    patch:
      tags:
        - Registry Sources
      parameters:
        - name: registry_id 
          in: path
          required: true
          description: The unique identifier of the registry source.
          schema:
            type: string
      responses:
        '200':
          description: Successfully retrieved the registry source.
          content:
            application/json:
              schema:
                type: object
                properties:
                  registry_source_id:
                    type: string
                    example: "reg_src_1234"
