openapi: 3.0.3
info:
  title: Registry Sources 
  version: ""
paths:
  /workspaces/{workspace_id}/sources/registries:
    get:
      tags:
        - Registry Sources
      security:
        - ClerkAuth: []
      parameters:
        - $ref: '../../params.yaml#/components/parameters/workspace_id'
      responses:
        '200':
          description: Successfully retrieved the registry sources for the workspace.
          content:
            application/json:
              schema:
                $ref: '../schemas/reg-src.yaml#/components/schemas/RegistrySourceList'
    post:
      tags:
        - Registry Sources
      security:
        - ClerkAuth: []
      parameters:
        - $ref: '../../params.yaml#/components/parameters/workspace_id'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../schemas/reg-src.yaml#/components/schemas/CreateRegistrySource'
      responses:
        '200':
          description: Successfully created the registry source for the workspace.
          content:
            application/json:
              schema:
                $ref: '../schemas/reg-src.yaml#/components/schemas/RegistrySource'
  /sources/registries/{registry_source_id}:
    get:
      tags:
        - Registry Sources
      security:
        - ClerkAuth: []
      parameters:
        - $ref: '../../params.yaml#/components/parameters/registry_source_id'
      responses:
        '200':
          description: Successfully retrieved the registry source.
          content:
            application/json:
              schema:
                $ref: '../schemas/reg-src.yaml#/components/schemas/RegistrySource'
    patch:
      tags:
        - Registry Sources
      security:
        - ClerkAuth: []
      parameters:
        - $ref: '../../params.yaml#/components/parameters/registry_source_id'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../schemas/reg-src.yaml#/components/schemas/UpdateRegistrySource'
      responses:
        '200':
          description: Successfully retrieved the registry source.
          content:
            application/json:
              schema:
                $ref: '../schemas/reg-src.yaml#/components/schemas/RegistrySource'
  /sources/registries/{registry_source_id}/compose_file:
    get:
      tags:
        - Registry Sources
      security:
        - ClerkAuth: []
      parameters:
        - $ref: '../../params.yaml#/components/parameters/registry_source_id'
      responses:
        '200':
          description: Successfully retrieved the compose file for the registry source.
          content:
            application/json:
              schema:
                $ref: '../schemas/artifact.yaml#/components/schemas/ComposeFile'
