openapi: 3.0.3
info:
  title: Repositories 
  version: ""
paths:
  /integrations/dockerhub/{dockerhub_integration_id}/repositories/external:
    get:
      tags:
        - Repositories
      security:
        - ClerkAuth: []
      parameters:
        - $ref: '../../params.yaml#/components/parameters/dockerhub_integration_id'
      responses:
        '200':
          description: Successfully retrieved the repositories for the dockerhub integration.
          content:
            application/json:
              schema:
                $ref: '../schemas/repo.yaml#/components/schemas/ExternalRepositoryList'
  /integrations/gar/{gar_integration_id}/repositories/external:
    get:
      tags:
        - Repositories
      security:
        - ClerkAuth: []
      parameters:
        - $ref: '../../params.yaml#/components/parameters/gar_integration_id'
      responses:
        '200':
          description: Successfully retrieved the repositories for the google artifact registry integration.
          content:
            application/json:
              schema:
                $ref: '../schemas/repo.yaml#/components/schemas/ExternalRepositoryList'
  /workspaces/{workspace_id}/repositories/external:
    get:
      tags:
        - Repositories
      security:
        - ClerkAuth: []
      parameters:
        - $ref: '../../params.yaml#/components/parameters/workspace_id'
      responses:
        '200':
          description: Successfully retrieved the repositories for the workspace.
          content:
            application/json:
              schema:
                $ref: '../schemas/repo.yaml#/components/schemas/ExternalRepositoryList'
  /repositories/{repository_id}:
    get:
      tags:
        - Repositories
      security:
        - ClerkAuth: []
      parameters:
        - $ref: '../../params.yaml#/components/parameters/repository_id'
      responses:
        '200':
          description: Successfully retrieved the repository.
          content:
            application/json:
              schema:
                $ref: '../schemas/repo.yaml#/components/schemas/Repository'
  /repositories/{repository_id}/images/external:
    get:
      tags:
        - Repositories
      security:
        - ClerkAuth: []
      parameters:
        - $ref: '../../params.yaml#/components/parameters/repository_id'
      responses:
        '200':
          description: Successfully retrieved the images for the repository.
          content:
            application/json:
              schema:
                $ref: '../schemas/repo.yaml#/components/schemas/ExternalImageList'
