openapi: 3.0.3
info:
  title: Artifacts
  version: ""
components:
  responses:
    DuplicateArtifact:
      description: Unable to create artifact since another artifact with identical content already exists
      content:
        application/json:
          schema:
            title: Error
            type: object
            required:
              - error
            properties:
              error:
                $ref: '../errors/artifacts.yaml#/components/schemas/DuplicateArtifact'
paths: {}
