openapi: 3.0.3
info:
  title: Artifacts
  version: ""
components:
  responses:
    InvalidComposeFile:
      description: The compose file is invalid.
      content:
        application/json:
          schema:
            $ref: '../errors/registry_sources.yaml#/components/schemas/InvalidComposeFile'
    RepositoryNotFound:
      description: The repository does not exist.
      content:
        application/json:
          schema:
            $ref: '../errors/registry_sources.yaml#/components/schemas/RepositoryNotFound'
paths: {}
