openapi: 3.0.3
info:
  title: Compose File
  version: ""
components:
  schemas:

    VerifyComposeFile:
      title: Validate Compose File
      type: object
      required:
        - object
        - content
      properties:
        object:
          type: string
          example: "compose_file"
        content:
          type: string
          example: "name: miru\nservices:\n  redis:\n  image: redis:latest\n  restart: always"

    VerifiedComposeFileResponse:
      title: Verified Compose File Response
      type: object
      required:
        - object
        - content
        - is_valid
        - is_schema_valid
        - images
      properties:
        object:
          type: string
          example: "compose_file"
        content:
          type: string
          example: "name: miru\nservices:\n  redis:\n  image: redis:latest\n  restart: always"
        is_valid: 
          type: boolean
          example: false 
        is_schema_valid:
          type: boolean
          example: true
        images:
          type: array
          items:
            $ref: "#/components/schemas/ComposeFileImageList"

    ComposeFileImage:
      title: Compose File Image
      allOf:
        - $ref: "./image.yaml#/components/schemas/ExternalContainerImage"
        - type: object
          required:
            - is_valid
          properties:
            is_valid:
              type: boolean
              example: false 

    ComposeFileImageList:
      title: Compose File Image List
      type: object
      required:
        - object
        - data
      properties:
        object:
          type: string
          example: "list"
        data:
          type: array
          items:
            $ref: "#/components/schemas/ComposeFileImage"

paths: {}
