openapi: 3.0.3
info:
  title: Repository Schemas
  version: ""
components:
  schemas:
    ContainerRepositoryType:
      title: Container Repository Type
      type: string
      enum:
        - gar
        - dockerhub
      example: "gar"
    ExternalContainerRepository:
      title: External Container Repository
      type: object
      required:
        - object
        - registry_url
        - account_login
        - name
        - uri
        - type
        - description
        - bytes
      properties:
        object:
          type: string
          example: "external_container_repository"
        registry_url:
          type: string
          example: "us-central1-docker.pkg.dev/container-integration"
        account_login:
          type: string
          example: "container-integration"
        name:
          type: string
          example: "django"
        uri:
          type: string
          example: "us-central1-docker.pkg.dev/container-integration/miru/django"
        type:
          $ref: "#/components/schemas/ContainerRepositoryType"
        description:
          type: string
          example: "A repository for the miru/django image"
          nullable: true
        bytes:
          type: integer
          format: int64
          description: "The size of the repository in bytes"
          example: 506406741
          nullable: true
    ExternalContainerRepositoryList:
      title: External Container Repository List
      type: object
      required:
        - object
        - data
      properties:
        object:
          type: string
          example: "list"
        data:
          type: array
          items:
            $ref: "#/components/schemas/ExternalContainerRepository"
    ContainerRepository:
      title: Container Repository 
      type: object
      required:
        - object
        - id
        - registry_url
        - account_login
        - name
        - uri
        - type
      properties:
        object:
          type: string
          example: "container_repository"
        id:
          type: string
          example: "cont_repo_123"
        registry_url:
          type: string
          example: "us-central1-docker.pkg.dev/container-integration"
        account_login:
          type: string
          example: "container-integration"
        name:
          type: string
          example: "django"
        uri:
          type: string
          example: "us-central1-docker.pkg.dev/container-integration/miru/django"
        type:
          $ref: "#/components/schemas/ContainerRepositoryType"
    ContainerRepositoryList:
      title: Container Repository List
      type: object
      required:
        - object
        - data
      properties:
        object:
          type: string
          example: "list"
        data:
          type: array
          items:
            $ref: "#/components/schemas/ContainerRepository"
paths: {}
