openapi: 3.0.3
info:
  title: Deploy Schemas
  version: ""
components: 
  schemas: 
    BaseDevice:
      title: Device
      type: object
      required:
        - object
        - id
        - name
        - hardware
        - operating_system
        - architecture
        - status
        - last_reported_status
        - miru_version
        - created_at
        - synced_at
        - group
      properties:
        object:
          type: string
          example: "device"
        id:
          type: string
          example: "device_1234"
        name:
          type: string
          example: "my-device"
        hardware:
          type: string
          example: "raspberry-pi"
        operating_system:
          type: string
          example: "ubuntu"
          nullable: true
        architecture:
          type: string
          example: "arm64"
          nullable: true
        status:
          type: string
          example: "offline"
        last_reported_status:
          type: string
          example: "active"
        miru_version:
          type: string
          example: "0.5.1"
          nullable: true
        created_at:
          type: string
          format: date-time
          example: "2024-11-03T14:19:50Z"
        synced_at:
          type: string
          format: date-time
    
    Device:
      allOf:
        - $ref: "./device.yaml#/components/schemas/BaseDevice"
        - type: object
          properties:
            group:
              $ref: "./group.yaml#/components/schemas/BaseGroup"

paths: {}
        
        
        
        
        
        