openapi: 3.0.3
info:
  title: GitHub Schemas
  version: ""
components:
  schemas:
    GitHubSource:
      title: GitHub Source
      type: object
      required:
        - id
        - object
        - name
        - repository_id
        - repository_name
        - branch
        - build_path
        - deleted
      properties:
        id:
          type: string
          example: "gh_src_123"
        object:
          type: string
          example: "github_source"
        name:
          type: string
          example: "e2e-tests"
        repository_id:
          type: integer 
          format: int64
          example: "12345"
        repository_name:
          type: string
          example: "bensmidt/e2e-tests"
        branch:
          type: string
          example: "main"
        build_path:
          type: string
          example: "path/to/compose/file/"
        deleted:
          type: boolean
          example: false

    GitHubSourceList:
      title: GitHub Source List
      type: object
      required:
        - object
        - data
      properties:
        object:
          type: string
          example: "list"
        data:
          type: array
          items:
            $ref: "#/components/schemas/GitHubSource"

    GitHubCommitter:
      title: GitHub Committer
      type: object
      required:
        - id
        - object
        - login
        - type
        - html_url
        - avatar_url
      properties:
        id:
          type: integer
          format: int64
          example: 92611223
        object:
          type: string
          example: "github_account"
        login:
          type: string
          example: "bensmidt"
        type:
          type: string
          example: "User"
        html_url:
          type: string
          example: "https://github.com/bensmidt"
        avatar_url:
          type: string
          example: "https://avatars.githubusercontent.com/u/92611223?v=4"

    GitHubCommit:
      title: GitHub Commit
      type: object
      required:
        - object
        - sha
        - message
        - html_url
        - pushed_at
        - committer
        - is_built
        - artifact_id
      properties:
        object:
          type: string
          example: "github_commit"
        sha:
          type: string
          example: "94d8a2681f1ef81b0362cdb77bf37691bc1d2b03"
        message:
          type: string
          example: "Fixes a bug"
        html_url:
          type: string
          example: "https://github.com/bensmidt/test-repo/commit/94d8a2681f1ef81b0362cdb77bf37691bc1d2b03"
        pushed_at:
          type: string
          format: date-time
          example: "2024-01-01T00:00:00Z"
        committer:
          $ref: '#/components/schemas/GitHubCommitter'
        is_built:
          type: boolean
          example: true
        artifacts:
          $ref: "#/components/schemas/GitHubCommitArtifactList"

    GitHubCommitArtifactList:
      title: GitHub Commit Artifact List
      type: object
      required:
        - object
        - data
      properties:
        object:
          type: string
          example: "list"
        data:
          type: array
          items:
            $ref: "#/components/schemas/GitHubCommitArtifact"

    GitHubCommitArtifact:
      title: GitHub Commit Artifact
      type: object
      required:
        - id 
        - object
        - status
      properties:
        object:
          type: string
          example: "artifact"
        id:
          type: string
          example: "art_123"
        status:
          type: string
          example: "failed"


    GitHubCommitList:
      title: GitHub CommitList
      type: object
      required:
        - object
        - data
      properties:
        object:
          type: string
          example: "list"
        data:
          type: array
          items:
            $ref: '#/components/schemas/GitHubCommit'

    GitHubRepository:
      title: GitHub Repository
      type: object
      required:
        - object
        - id
        - name
        - full_name
        - html_url
        - clone_url
      properties:
        id:
          type: integer
          format: int64
          example: 1234567890
        object:
          type: string
          example: "github_repository"
        name:
          type: string
          example: "e2e-tests"
        full_name:
          type: string
          example: "bensmidt/e2e-tests"
        html_url:
          type: string
          example: "https://github.com/bensmidt/e2e-tests"

    GitHubSourceCommits:
      title: GitHubSourceCommits
      type: object
      required:
        - object
        - repository
        - commits
        - branch
      properties:
        object:
          type: string
          example: "github_source_commits"
        repository:
          $ref: '#/components/schemas/GitHubRepository'
        branch:
          type: string
          example: "main"
        commits:
          $ref: '#/components/schemas/GitHubCommitList'

paths: {}

