openapi: 3.0.3
info:
  title: Deploy Schemas
  version: ""
components: 
  schemas: 
    BaseGroup:
      title: BaseGroup
      type: object
      required:
        - object
        - id
        - name
      properties:
        object:
          type: string
          example: "group"
        id:
          type: string
          example: "group_1234"
        name:
          type: string
          example: "my-group"

    Group:
      allOf:
        - $ref: "./group.yaml#/components/schemas/BaseGroup"
        - type: object
          properties:
            devices:
              type: object
              required:
                - object
                - data
              properties:
                object:
                  type: string
                  example: "list"
                data:
                  type: array
                  items:
                    $ref: "#/components/schemas/Device"
            github_sources:
              $ref: "./gh-src.yaml#/components/schemas/GitHubSourceList"


    Device:
      allOf:
        - $ref: "./device.yaml#/components/schemas/BaseDevice"
        - type: object
          properties:
            containers:
              type: object 
              required:
                - object
                - data
              properties:
                object:
                  type: string
                  example: "list"
                data:
                  type: array
                  items:
                    $ref: "#/components/schemas/Container"
            deployments:
              type: object
              required:
                - object
                - data
              properties:
                object:
                  type: string
                  example: "list"
                data:
                  type: array
                  items:
                    $ref: "#/components/schemas/Deployment"

    Container:
      title: Container
      type: object
      required:
        - object
        - id
        - status
      properties:
        object:
          type: string
          example: "container"
        id:
          type: string
          example: "container_1234"
        status:
          type: string
          example: "running"
    
    Deployment:
      title: Deployment
      type: object
      required:
        - object
        - id
        - status
        - activity_status
        - error_status
      properties:
        object:
          type: string
          example: "deployment"
        id:
          type: string
          example: "deployment_1234"
        status:
          type: string
          example: "running"
        activity_status:
          type: string
          example: "active"
        error_status:
          type: string
          example: "none"



paths: {}
