openapi: 3.0.3
info:
  title: Registry Sources Schemas
  version: ""
components:
  schemas:
    RepositoryListItemWithIsExtra:
      title: Repository List Item With Is Extra (Registry Source)
      allOf:
        - $ref: '../schemas/repo.yaml#/components/schemas/RepositoryListItem'
        - type: object
          properties:
            is_extra:
              type: boolean
              example: true
    RegistrySourceListItem:
      title: Registry Source List Item
      type: object
      properties:
        id:
          type: string
          example: "reg_src_1234"
        name:
          type: string
          example: "Ad Display V2.2.1"
        repos:
          type: array
          items:
            $ref: './repo.yaml#/components/schemas/RepositoryListItem'
        aarch64:
          type: boolean
          example: true
        x86_64:
          type: boolean
          example: false
    RegistrySource:
      title: Registry Source
      allOf:
        - $ref: '#/components/schemas/RegistrySourceListItem'
        - type: object
          properties:
            repos:
              type: array
              items:
                $ref: '#/components/schemas/RepositoryListItemWithIsExtra'
    CreateRegistrySource:
      title: Create Registry Source
      type: object
      properties:
        name:
          type: string
          example: "Ad Display V2.2.1"
        compose_file:
          type: string
          example: "name: miru\nservices:\n  redis:\n  image: redis:latest\n  restart: always"
        extra_repos:
          type: array
          items:
            type: string
          example:
            - "docker.io/redis"
            - "us-central1-docker.pkg.dev/container-integration/miru/django"
        aarch64:
          type: boolean
          example: true
        x86_64:
          type: boolean
          example: false 
    UpdateRegistrySource:
      title: Update Registry Source
      type: object
      properties:
        name:
          type: string
          example: "Ad Display V2.2.1"
        compose_file:
          type: string
          example: "name: miru\nservices:\n  redis:\n  image: redis:latest\n  restart: always"
        extra_repos:
          type: array
          items:
            type: string
          example:
            - "docker.io/redis"
            - "us-central1-docker.pkg.dev/container-integration/miru/django"
        aarch64:
          type: boolean
          example: true
        x86_64:
          type: boolean
          example: false 
paths: {}