openapi: 3.0.3
info:
  title: Registry Source Schemas
  version: ""
components:
  schemas:
    RegistrySourceContainerRepository:
      title: Container Repository With Is Extra (Registry Source)
      type: object
      required:
        - is_extra
        - compose_service
      allOf:
        - $ref: '../schemas/cont-repo.yaml#/components/schemas/ContainerRepository'
        - type: object
          properties:
            is_extra:
              type: boolean
              example: true
            compose_service:
              type: string
              example: "database"
              nullable: true
    RegistrySourceContainerRepositoryList:
      title: Container Repository List With Is Extra (Registry Source)
      type: object
      required:
        - object
        - data
      properties:
        object:
          type: string
          example: "list"
        data:
          type: array
          items:
            $ref: '#/components/schemas/RegistrySourceContainerRepository'
    RegistrySource:
      title: Registry Source 
      type: object
      required:
        - id
        - object
        - name
        - repositories
        - aarch64
        - x86_64
        - created_at
        - updated_at
      properties:
        id:
          type: string
          example: "reg_src_1234"
        object:
          type: string
          example: "registry_source"
        name:
          type: string
          example: "Ad Display V2.2.1"
        repositories:
          $ref: '#/components/schemas/RegistrySourceContainerRepositoryList'
        aarch64:
          type: boolean
          example: true
        x86_64:
          type: boolean
          example: false
        created_at:
          type: string
          format: date-time
          example: "2024-10-26 20:00:23.742537+00"
        updated_at:
          type: string
          format: date-time
          example: "2024-10-26 20:00:23.742537+00"
    RegistrySourceList:
      title: Registry Source List
      type: object
      required:
        - object
        - data
      properties:
        object:
          type: string
          example: "list"
        data:
          type: array
          items:
            $ref: '#/components/schemas/RegistrySource'
    CreateRegistrySource:
      title: Create Registry Source
      type: object
      required:
        - name
        - compose_file
        - extra_repositories
        - aarch64
        - x86_64
      properties:
        name:
          type: string
          example: "Ad Display V2.2.1"
        compose_file:
          type: string
          example: "name: miru\nservices:\n  redis:\n  image: redis:latest\n  restart: always"
        extra_repositories:
          type: array
          items:
            type: string
          example:
            - "docker.io/redis"
            - "us-central1-docker.pkg.dev/container-integration/miru/django"
        aarch64:
          type: boolean
          example: true
        x86_64:
          type: boolean
          example: false 
    UpdateRegistrySource:
      title: Update Registry Source
      type: object
      required:
        - name
        - compose_file
        - extra_repositories
        - aarch64
        - x86_64
      properties:
        name:
          type: string
          example: "Ad Display V2.2.1"
        compose_file:
          type: string
          example: "name: miru\nservices:\n  redis:\n  image: redis:latest\n  restart: always"
        extra_repositories:
          type: array
          items:
            type: string
          example:
            - "docker.io/redis"
            - "us-central1-docker.pkg.dev/container-integration/miru/django"
        aarch64:
          type: boolean
          example: true
        x86_64:
          type: boolean
          example: false 
paths: {}