openapi: 3.0.3
info:
  title: Repository Schemas
  version: ""
components:
  schemas:

    ExternalRepository:
      title: External Repository
      type: object 
      required:
        - registry_url
        - name
        - uri
      properties:
        object:
          type: string
          example: "external_repository"
        registry_url:
          type: string
          example: "us-central1-docker.pkg.dev/container-integration"
        name:
          type: string
          example: "miru/django"
        uri:
          type: string
          example: "us-central1-docker.pkg.dev/container-integration/miru/django"
    ExternalRepositoryList:
      title: External Repository List
      type: object
      properties:
        object:
          type: string
          example: "list"
        data:
          type: array
          items:
            $ref: "#/components/schemas/ExternalRepository"
    Repository:
      title: Repository 
      allOf:
        - $ref: '#/components/schemas/ExternalRepository'
        - type: object
          required:
            - id
            - object
          properties:
            object:
              type: string
              example: "repository"
            id:
              type: string
              example: "repo_123"
    RepositoryList:
      title: Repository List
      type: object
      properties:
        object:
          type: string
          example: "list"
        data:
          type: array
          items:
            $ref: "#/components/schemas/Repository"
    ExternalImage:
      title: External Image 
      type: object 
      required:
        - digest
        - tags
        - uri
        - bytes
        - uploaded_at
      properties:
        object:
          type: string
          example: "external_image"
        digest:
          type: string
          example: "sha256:123abc"
        tags:
          type: array
          items:
            type: string
            example: "latest"
          example:
            - "latest"
            - "v1.0.0"
            - "stable"
        uri:
          type: string
          example: "docker.io/redis:latest"
        bytes:
          type: integer
          example: 392510987
        uploaded_at:
          type: string
          example: "2021-01-01T00:00:00Z"
    ExternalImageList:
      title: External Image List
      type: object
      properties:
        object:
          type: string
          example: "list"
        data:
          type: array
          items:
            $ref: "#/components/schemas/ExternalImage"
paths: {}
