openapi: 3.0.3
info:
  title: API with Bearer Token Authentication
  version: ""
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: The Bearer token for the device
paths: {}