// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1.0
 */

package openapi




type Device1AllOfDeployments struct {

	Object string `json:"object"`

	Data []BaseDeployment `json:"data"`
}

// AssertDevice1AllOfDeploymentsRequired checks if the required fields are not zero-ed
func AssertDevice1AllOfDeploymentsRequired(obj Device1AllOfDeployments) error {
	elements := map[string]interface{}{
		"object": obj.Object,
		"data": obj.Data,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Data {
		if err := AssertBaseDeploymentRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertDevice1AllOfDeploymentsConstraints checks if the values respects the defined constraints
func AssertDevice1AllOfDeploymentsConstraints(obj Device1AllOfDeployments) error {
	for _, el := range obj.Data {
		if err := AssertBaseDeploymentConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
