// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1.0
 */

package openapi




type VerifiedComposeFileResponse struct {

	Object string `json:"object"`

	Content string `json:"content"`

	IsValid bool `json:"is_valid"`

	IsSchemaValid bool `json:"is_schema_valid"`

	Images []ComposeFileImageList `json:"images"`
}

// AssertVerifiedComposeFileResponseRequired checks if the required fields are not zero-ed
func AssertVerifiedComposeFileResponseRequired(obj VerifiedComposeFileResponse) error {
	elements := map[string]interface{}{
		"object": obj.Object,
		"content": obj.Content,
		"is_valid": obj.IsValid,
		"is_schema_valid": obj.IsSchemaValid,
		"images": obj.Images,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Images {
		if err := AssertComposeFileImageListRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertVerifiedComposeFileResponseConstraints checks if the values respects the defined constraints
func AssertVerifiedComposeFileResponseConstraints(obj VerifiedComposeFileResponse) error {
	for _, el := range obj.Images {
		if err := AssertComposeFileImageListConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
