// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1.0
 */

package openapi




type Repository struct {

	Object string `json:"object"`

	RegistryUrl string `json:"registry_url"`

	Name string `json:"name"`

	Uri string `json:"uri"`

	Id string `json:"id"`
}

// AssertRepositoryRequired checks if the required fields are not zero-ed
func AssertRepositoryRequired(obj Repository) error {
	elements := map[string]interface{}{
		"object": obj.Object,
		"registry_url": obj.RegistryUrl,
		"name": obj.Name,
		"uri": obj.Uri,
		"id": obj.Id,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRepositoryConstraints checks if the values respects the defined constraints
func AssertRepositoryConstraints(obj Repository) error {
	return nil
}
