// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1.0
 */

package openapi




type UpdateRegistrySourceExtraRepositories struct {

	Data []string `json:"data,omitempty"`
}

// AssertUpdateRegistrySourceExtraRepositoriesRequired checks if the required fields are not zero-ed
func AssertUpdateRegistrySourceExtraRepositoriesRequired(obj UpdateRegistrySourceExtraRepositories) error {
	return nil
}

// AssertUpdateRegistrySourceExtraRepositoriesConstraints checks if the values respects the defined constraints
func AssertUpdateRegistrySourceExtraRepositoriesConstraints(obj UpdateRegistrySourceExtraRepositories) error {
	return nil
}
