// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1.0
 */

package openapi




type GitHubCommit struct {

	Object string `json:"object,omitempty"`

	Sha string `json:"sha,omitempty"`

	Message string `json:"message,omitempty"`

	HtmlUrl string `json:"html_url,omitempty"`

	Committer GitHubCommitter `json:"committer,omitempty"`
}

// AssertGitHubCommitRequired checks if the required fields are not zero-ed
func AssertGitHubCommitRequired(obj GitHubCommit) error {
	if err := AssertGitHubCommitterRequired(obj.Committer); err != nil {
		return err
	}
	return nil
}

// AssertGitHubCommitConstraints checks if the values respects the defined constraints
func AssertGitHubCommitConstraints(obj GitHubCommit) error {
	if err := AssertGitHubCommitterConstraints(obj.Committer); err != nil {
		return err
	}
	return nil
}
