// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1.0
 */

package openapi




type DuplicateArtifact struct {

	Code string `json:"code"`

	Params DuplicateArtifactParams `json:"params"`

	Message string `json:"message"`

	DebugMessage string `json:"debug_message,omitempty"`
}

// AssertDuplicateArtifactRequired checks if the required fields are not zero-ed
func AssertDuplicateArtifactRequired(obj DuplicateArtifact) error {
	elements := map[string]interface{}{
		"code": obj.Code,
		"params": obj.Params,
		"message": obj.Message,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertDuplicateArtifactParamsRequired(obj.Params); err != nil {
		return err
	}
	return nil
}

// AssertDuplicateArtifactConstraints checks if the values respects the defined constraints
func AssertDuplicateArtifactConstraints(obj DuplicateArtifact) error {
	if err := AssertDuplicateArtifactParamsConstraints(obj.Params); err != nil {
		return err
	}
	return nil
}
