// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1.0
 */

package openapi




type GroupDeviceContainer struct {

	Object string `json:"object"`

	Id string `json:"id"`

	Status string `json:"status"`
}

// AssertGroupDeviceContainerRequired checks if the required fields are not zero-ed
func AssertGroupDeviceContainerRequired(obj GroupDeviceContainer) error {
	elements := map[string]interface{}{
		"object": obj.Object,
		"id": obj.Id,
		"status": obj.Status,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertGroupDeviceContainerConstraints checks if the values respects the defined constraints
func AssertGroupDeviceContainerConstraints(obj GroupDeviceContainer) error {
	return nil
}
