// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1.0
 */

package openapi


import (
	"time"
)



type GitHubSourceDataRepository struct {

	Id int64 `json:"id"`

	HtmlUrl string `json:"html_url"`

	CloneUrl string `json:"clone_url"`

	FullName string `json:"full_name"`

	PushedAt time.Time `json:"pushed_at"`
}

// AssertGitHubSourceDataRepositoryRequired checks if the required fields are not zero-ed
func AssertGitHubSourceDataRepositoryRequired(obj GitHubSourceDataRepository) error {
	elements := map[string]interface{}{
		"id": obj.Id,
		"html_url": obj.HtmlUrl,
		"clone_url": obj.CloneUrl,
		"full_name": obj.FullName,
		"pushed_at": obj.PushedAt,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertGitHubSourceDataRepositoryConstraints checks if the values respects the defined constraints
func AssertGitHubSourceDataRepositoryConstraints(obj GitHubSourceDataRepository) error {
	return nil
}
