// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1.0
 */

package openapi




type GitHubCommitter struct {

	Id int64 `json:"id"`

	Object string `json:"object,omitempty"`

	Login string `json:"login"`

	Type string `json:"type"`

	HtmlUrl string `json:"html_url"`

	AvatarUrl string `json:"avatar_url"`
}

// AssertGitHubCommitterRequired checks if the required fields are not zero-ed
func AssertGitHubCommitterRequired(obj GitHubCommitter) error {
	elements := map[string]interface{}{
		"id": obj.Id,
		"login": obj.Login,
		"type": obj.Type,
		"html_url": obj.HtmlUrl,
		"avatar_url": obj.AvatarUrl,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertGitHubCommitterConstraints checks if the values respects the defined constraints
func AssertGitHubCommitterConstraints(obj GitHubCommitter) error {
	return nil
}
