// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1.0
 */

package openapi




type GitHubRepository struct {

	Id int64 `json:"id"`

	Object string `json:"object,omitempty"`

	Name string `json:"name"`

	FullName string `json:"full_name"`

	HtmlUrl string `json:"html_url"`
}

// AssertGitHubRepositoryRequired checks if the required fields are not zero-ed
func AssertGitHubRepositoryRequired(obj GitHubRepository) error {
	elements := map[string]interface{}{
		"id": obj.Id,
		"name": obj.Name,
		"full_name": obj.FullName,
		"html_url": obj.HtmlUrl,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertGitHubRepositoryConstraints checks if the values respects the defined constraints
func AssertGitHubRepositoryConstraints(obj GitHubRepository) error {
	return nil
}
