// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1.0
 */

package openapi




type RecordNotFoundError struct {

	Code string `json:"code"`

	Params RecordNotFoundErrorParams `json:"params"`

	Message string `json:"message"`
}

// AssertRecordNotFoundErrorRequired checks if the required fields are not zero-ed
func AssertRecordNotFoundErrorRequired(obj RecordNotFoundError) error {
	elements := map[string]interface{}{
		"code": obj.Code,
		"params": obj.Params,
		"message": obj.Message,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertRecordNotFoundErrorParamsRequired(obj.Params); err != nil {
		return err
	}
	return nil
}

// AssertRecordNotFoundErrorConstraints checks if the values respects the defined constraints
func AssertRecordNotFoundErrorConstraints(obj RecordNotFoundError) error {
	if err := AssertRecordNotFoundErrorParamsConstraints(obj.Params); err != nil {
		return err
	}
	return nil
}
