// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Miru API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1.0
 */

package openapi




type RegistrySourceContainerRepositoryList struct {

	Object string `json:"object"`

	Data []RegistrySourceContainerRepository `json:"data"`
}

// AssertRegistrySourceContainerRepositoryListRequired checks if the required fields are not zero-ed
func AssertRegistrySourceContainerRepositoryListRequired(obj RegistrySourceContainerRepositoryList) error {
	elements := map[string]interface{}{
		"object": obj.Object,
		"data": obj.Data,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRegistrySourceContainerRepositoryListConstraints checks if the values respects the defined constraints
func AssertRegistrySourceContainerRepositoryListConstraints(obj RegistrySourceContainerRepositoryList) error {
	return nil
}
