/*
Miru API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ExternalImageList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExternalImageList{}

// ExternalImageList struct for ExternalImageList
type ExternalImageList struct {
	Object *string `json:"object,omitempty"`
	Data []ExternalImage `json:"data,omitempty"`
}

// NewExternalImageList instantiates a new ExternalImageList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExternalImageList() *ExternalImageList {
	this := ExternalImageList{}
	return &this
}

// NewExternalImageListWithDefaults instantiates a new ExternalImageList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExternalImageListWithDefaults() *ExternalImageList {
	this := ExternalImageList{}
	return &this
}

// GetObject returns the Object field value if set, zero value otherwise.
func (o *ExternalImageList) GetObject() string {
	if o == nil || IsNil(o.Object) {
		var ret string
		return ret
	}
	return *o.Object
}

// GetObjectOk returns a tuple with the Object field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExternalImageList) GetObjectOk() (*string, bool) {
	if o == nil || IsNil(o.Object) {
		return nil, false
	}
	return o.Object, true
}

// HasObject returns a boolean if a field has been set.
func (o *ExternalImageList) HasObject() bool {
	if o != nil && !IsNil(o.Object) {
		return true
	}

	return false
}

// SetObject gets a reference to the given string and assigns it to the Object field.
func (o *ExternalImageList) SetObject(v string) {
	o.Object = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ExternalImageList) GetData() []ExternalImage {
	if o == nil || IsNil(o.Data) {
		var ret []ExternalImage
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExternalImageList) GetDataOk() ([]ExternalImage, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ExternalImageList) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []ExternalImage and assigns it to the Data field.
func (o *ExternalImageList) SetData(v []ExternalImage) {
	o.Data = v
}

func (o ExternalImageList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExternalImageList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Object) {
		toSerialize["object"] = o.Object
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableExternalImageList struct {
	value *ExternalImageList
	isSet bool
}

func (v NullableExternalImageList) Get() *ExternalImageList {
	return v.value
}

func (v *NullableExternalImageList) Set(val *ExternalImageList) {
	v.value = val
	v.isSet = true
}

func (v NullableExternalImageList) IsSet() bool {
	return v.isSet
}

func (v *NullableExternalImageList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExternalImageList(val *ExternalImageList) *NullableExternalImageList {
	return &NullableExternalImageList{value: val, isSet: true}
}

func (v NullableExternalImageList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExternalImageList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


