/*
Miru API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GitHubCommitArtifactList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GitHubCommitArtifactList{}

// GitHubCommitArtifactList struct for GitHubCommitArtifactList
type GitHubCommitArtifactList struct {
	Object string `json:"object"`
	Data []GitHubCommitArtifact `json:"data"`
}

type _GitHubCommitArtifactList GitHubCommitArtifactList

// NewGitHubCommitArtifactList instantiates a new GitHubCommitArtifactList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGitHubCommitArtifactList(object string, data []GitHubCommitArtifact) *GitHubCommitArtifactList {
	this := GitHubCommitArtifactList{}
	this.Object = object
	this.Data = data
	return &this
}

// NewGitHubCommitArtifactListWithDefaults instantiates a new GitHubCommitArtifactList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGitHubCommitArtifactListWithDefaults() *GitHubCommitArtifactList {
	this := GitHubCommitArtifactList{}
	return &this
}

// GetObject returns the Object field value
func (o *GitHubCommitArtifactList) GetObject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Object
}

// GetObjectOk returns a tuple with the Object field value
// and a boolean to check if the value has been set.
func (o *GitHubCommitArtifactList) GetObjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Object, true
}

// SetObject sets field value
func (o *GitHubCommitArtifactList) SetObject(v string) {
	o.Object = v
}

// GetData returns the Data field value
func (o *GitHubCommitArtifactList) GetData() []GitHubCommitArtifact {
	if o == nil {
		var ret []GitHubCommitArtifact
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GitHubCommitArtifactList) GetDataOk() ([]GitHubCommitArtifact, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *GitHubCommitArtifactList) SetData(v []GitHubCommitArtifact) {
	o.Data = v
}

func (o GitHubCommitArtifactList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GitHubCommitArtifactList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["object"] = o.Object
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *GitHubCommitArtifactList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"object",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGitHubCommitArtifactList := _GitHubCommitArtifactList{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGitHubCommitArtifactList)

	if err != nil {
		return err
	}

	*o = GitHubCommitArtifactList(varGitHubCommitArtifactList)

	return err
}

type NullableGitHubCommitArtifactList struct {
	value *GitHubCommitArtifactList
	isSet bool
}

func (v NullableGitHubCommitArtifactList) Get() *GitHubCommitArtifactList {
	return v.value
}

func (v *NullableGitHubCommitArtifactList) Set(val *GitHubCommitArtifactList) {
	v.value = val
	v.isSet = true
}

func (v NullableGitHubCommitArtifactList) IsSet() bool {
	return v.isSet
}

func (v *NullableGitHubCommitArtifactList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGitHubCommitArtifactList(val *GitHubCommitArtifactList) *NullableGitHubCommitArtifactList {
	return &NullableGitHubCommitArtifactList{value: val, isSet: true}
}

func (v NullableGitHubCommitArtifactList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGitHubCommitArtifactList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


