/*
Miru API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ArtifactWithGitHubSourceDataList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ArtifactWithGitHubSourceDataList{}

// ArtifactWithGitHubSourceDataList struct for ArtifactWithGitHubSourceDataList
type ArtifactWithGitHubSourceDataList struct {
	Object string `json:"object"`
	Data []ArtifactWithGitHubSourceData `json:"data"`
}

type _ArtifactWithGitHubSourceDataList ArtifactWithGitHubSourceDataList

// NewArtifactWithGitHubSourceDataList instantiates a new ArtifactWithGitHubSourceDataList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewArtifactWithGitHubSourceDataList(object string, data []ArtifactWithGitHubSourceData) *ArtifactWithGitHubSourceDataList {
	this := ArtifactWithGitHubSourceDataList{}
	this.Object = object
	this.Data = data
	return &this
}

// NewArtifactWithGitHubSourceDataListWithDefaults instantiates a new ArtifactWithGitHubSourceDataList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewArtifactWithGitHubSourceDataListWithDefaults() *ArtifactWithGitHubSourceDataList {
	this := ArtifactWithGitHubSourceDataList{}
	return &this
}

// GetObject returns the Object field value
func (o *ArtifactWithGitHubSourceDataList) GetObject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Object
}

// GetObjectOk returns a tuple with the Object field value
// and a boolean to check if the value has been set.
func (o *ArtifactWithGitHubSourceDataList) GetObjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Object, true
}

// SetObject sets field value
func (o *ArtifactWithGitHubSourceDataList) SetObject(v string) {
	o.Object = v
}

// GetData returns the Data field value
func (o *ArtifactWithGitHubSourceDataList) GetData() []ArtifactWithGitHubSourceData {
	if o == nil {
		var ret []ArtifactWithGitHubSourceData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ArtifactWithGitHubSourceDataList) GetDataOk() ([]ArtifactWithGitHubSourceData, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *ArtifactWithGitHubSourceDataList) SetData(v []ArtifactWithGitHubSourceData) {
	o.Data = v
}

func (o ArtifactWithGitHubSourceDataList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ArtifactWithGitHubSourceDataList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["object"] = o.Object
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *ArtifactWithGitHubSourceDataList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"object",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varArtifactWithGitHubSourceDataList := _ArtifactWithGitHubSourceDataList{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varArtifactWithGitHubSourceDataList)

	if err != nil {
		return err
	}

	*o = ArtifactWithGitHubSourceDataList(varArtifactWithGitHubSourceDataList)

	return err
}

type NullableArtifactWithGitHubSourceDataList struct {
	value *ArtifactWithGitHubSourceDataList
	isSet bool
}

func (v NullableArtifactWithGitHubSourceDataList) Get() *ArtifactWithGitHubSourceDataList {
	return v.value
}

func (v *NullableArtifactWithGitHubSourceDataList) Set(val *ArtifactWithGitHubSourceDataList) {
	v.value = val
	v.isSet = true
}

func (v NullableArtifactWithGitHubSourceDataList) IsSet() bool {
	return v.isSet
}

func (v *NullableArtifactWithGitHubSourceDataList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableArtifactWithGitHubSourceDataList(val *ArtifactWithGitHubSourceDataList) *NullableArtifactWithGitHubSourceDataList {
	return &NullableArtifactWithGitHubSourceDataList{value: val, isSet: true}
}

func (v NullableArtifactWithGitHubSourceDataList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableArtifactWithGitHubSourceDataList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


