/*
Miru API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VerifyComposeFile type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VerifyComposeFile{}

// VerifyComposeFile struct for VerifyComposeFile
type VerifyComposeFile struct {
	Object string `json:"object"`
	Content string `json:"content"`
}

type _VerifyComposeFile VerifyComposeFile

// NewVerifyComposeFile instantiates a new VerifyComposeFile object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVerifyComposeFile(object string, content string) *VerifyComposeFile {
	this := VerifyComposeFile{}
	this.Object = object
	this.Content = content
	return &this
}

// NewVerifyComposeFileWithDefaults instantiates a new VerifyComposeFile object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVerifyComposeFileWithDefaults() *VerifyComposeFile {
	this := VerifyComposeFile{}
	return &this
}

// GetObject returns the Object field value
func (o *VerifyComposeFile) GetObject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Object
}

// GetObjectOk returns a tuple with the Object field value
// and a boolean to check if the value has been set.
func (o *VerifyComposeFile) GetObjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Object, true
}

// SetObject sets field value
func (o *VerifyComposeFile) SetObject(v string) {
	o.Object = v
}

// GetContent returns the Content field value
func (o *VerifyComposeFile) GetContent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Content
}

// GetContentOk returns a tuple with the Content field value
// and a boolean to check if the value has been set.
func (o *VerifyComposeFile) GetContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Content, true
}

// SetContent sets field value
func (o *VerifyComposeFile) SetContent(v string) {
	o.Content = v
}

func (o VerifyComposeFile) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VerifyComposeFile) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["object"] = o.Object
	toSerialize["content"] = o.Content
	return toSerialize, nil
}

func (o *VerifyComposeFile) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"object",
		"content",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVerifyComposeFile := _VerifyComposeFile{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVerifyComposeFile)

	if err != nil {
		return err
	}

	*o = VerifyComposeFile(varVerifyComposeFile)

	return err
}

type NullableVerifyComposeFile struct {
	value *VerifyComposeFile
	isSet bool
}

func (v NullableVerifyComposeFile) Get() *VerifyComposeFile {
	return v.value
}

func (v *NullableVerifyComposeFile) Set(val *VerifyComposeFile) {
	v.value = val
	v.isSet = true
}

func (v NullableVerifyComposeFile) IsSet() bool {
	return v.isSet
}

func (v *NullableVerifyComposeFile) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVerifyComposeFile(val *VerifyComposeFile) *NullableVerifyComposeFile {
	return &NullableVerifyComposeFile{value: val, isSet: true}
}

func (v NullableVerifyComposeFile) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVerifyComposeFile) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


