openapi: 3.0.3
info:
  title: Miru API
  version: 0.1.0
servers:
  - url: https://api.miruml.com/{audience}/{version}
    description: Production
    variables:
      audience:
        default: internal
        enum:
          - internal
          - internal/devices
      version:
        default: v1
  - url: https://dev.api.miruml.com/{audience}/{version}
    description: Development 
    variables:
      audience:
        default: internal
        enum:
          - internal
          - internal/devices
      version:
        default: v1
  - url: https://localhost:8080/{audience}/{version}
    description: Local Development 
    variables:
      audience:
        default: internal
        enum:
          - internal
          - internal/devices
      version:
        default: v1
paths: 
  # artifacts
  /artifacts/{artifact_id}:
    $ref: './frontend/paths/artifacts.yaml#/paths/~1artifacts~1{artifact_id}'
  /artifacts/{artifact_id}/compose_file:
    $ref: './frontend/paths/artifacts.yaml#/paths/~1artifacts~1{artifact_id}~1compose_file'
  /sources/registries/{registry_source_id}/artifacts:
    $ref: './frontend/paths/artifacts.yaml#/paths/~1sources~1registries~1{registry_source_id}~1artifacts'
  /sources/github/{github_source_id}/artifacts:
    $ref: './frontend/paths/artifacts.yaml#/paths/~1sources~1github~1{github_source_id}~1artifacts'
  # registry sources
  /workspaces/{workspace_id}/sources/registries:
    $ref: './frontend/paths/reg-srcs.yaml#/paths/~1workspaces~1{workspace_id}~1sources~1registries'
  /sources/registries/{registry_source_id}:
    $ref: './frontend/paths/reg-srcs.yaml#/paths/~1sources~1registries~1{registry_source_id}'
  /sources/registries/{registry_source_id}/compose_file:
    $ref: './frontend/paths/reg-srcs.yaml#/paths/~1sources~1registries~1{registry_source_id}~1compose_file'
  # repositories
  /integrations/dockerhub/{dockerhub_integration_id}/repositories/external:
    $ref: './frontend/paths/repos.yaml#/paths/~1integrations~1dockerhub~1{dockerhub_integration_id}~1repositories~1external'
  /integrations/gar/{gar_integration_id}/repositories/external:
    $ref: './frontend/paths/repos.yaml#/paths/~1integrations~1gar~1{gar_integration_id}~1repositories~1external'
  /workspaces/{workspace_id}/repositories/external:
    $ref: './frontend/paths/repos.yaml#/paths/~1workspaces~1{workspace_id}~1repositories~1external'
  /repositories/{repository_id}:
    $ref: './frontend/paths/repos.yaml#/paths/~1repositories~1{repository_id}'
  /repositories/{repository_id}/images/external:
    $ref: './frontend/paths/repos.yaml#/paths/~1repositories~1{repository_id}~1images~1external'
