openapi: 3.0.3
info:
  title: Miru API
  version: 0.1.0
servers:
  - url: http://localhost:8080/{audience}/{version}
    description: Local Development 
    variables:
      audience:
        default: internal
        enum:
          - internal
          - internal/devices
      version:
        default: v1
  - url: https://dev.api.miruml.com/{audience}/{version}
    description: Development 
    variables:
      audience:
        default: internal
        enum:
          - internal
          - internal/devices
      version:
        default: v1
  - url: https://api.miruml.com/{audience}/{version}
    description: Production
    variables:
      audience:
        default: internal
        enum:
          - internal
          - internal/devices
      version:
        default: v1
components:
  securitySchemes:
    ClerkAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT # Optional, indicates token format
security:
  - ClerkAuth: []
paths: 
  # artifacts
  /artifacts/{artifact_id}:
    $ref: './frontend/paths/artifacts.yaml#/paths/~1artifacts~1{artifact_id}'
  /artifacts/{artifact_id}/compose_file:
    $ref: './frontend/paths/artifacts.yaml#/paths/~1artifacts~1{artifact_id}~1compose_file'
  /groups/{group_id}/artifacts:
    $ref: './frontend/paths/artifacts.yaml#/paths/~1groups~1{group_id}~1artifacts'
  /sources/registry/{registry_source_id}/artifacts:
    $ref: './frontend/paths/artifacts.yaml#/paths/~1sources~1registry~1{registry_source_id}~1artifacts'
  /sources/github/{github_source_id}/artifacts:
    $ref: './frontend/paths/artifacts.yaml#/paths/~1sources~1github~1{github_source_id}~1artifacts'

  # deployments
  /workspaces/{workspace_id}/deploy:
    $ref: './frontend/paths/deployments.yaml#/paths/~1workspaces~1{workspace_id}~1deploy'

  # github sources
  /sources/github/{github_source_id}/commits:
    $ref: './frontend/paths/gh-src.yaml#/paths/~1sources~1github~1{github_source_id}~1commits'

  # images
  /repositories/container/{container_repository_id}/images/external:
    $ref: './frontend/paths/images.yaml#/paths/~1repositories~1container~1{container_repository_id}~1images~1external'

  # registry sources
  /workspaces/{workspace_id}/sources/registry:
    $ref: './frontend/paths/reg-srcs.yaml#/paths/~1workspaces~1{workspace_id}~1sources~1registry'
  /sources/registry/{registry_source_id}:
    $ref: './frontend/paths/reg-srcs.yaml#/paths/~1sources~1registry~1{registry_source_id}'
  /sources/registry/{registry_source_id}/compose_file:
    $ref: './frontend/paths/reg-srcs.yaml#/paths/~1sources~1registry~1{registry_source_id}~1compose_file'

  # repositories
  /integrations/dockerhub/{dockerhub_integration_id}/repositories/external:
    $ref: './frontend/paths/cont-repos.yaml#/paths/~1integrations~1dockerhub~1{dockerhub_integration_id}~1repositories~1external'
  /integrations/gar/{gar_integration_id}/repositories/external:
    $ref: './frontend/paths/cont-repos.yaml#/paths/~1integrations~1gar~1{gar_integration_id}~1repositories~1external'
  /workspaces/{workspace_id}/repositories/container/external:
    $ref: './frontend/paths/cont-repos.yaml#/paths/~1workspaces~1{workspace_id}~1repositories~1container~1external'
  /repositories/container/{container_repository_id}:
    $ref: './frontend/paths/cont-repos.yaml#/paths/~1repositories~1container~1{container_repository_id}'

  # error examples
  /example/errors/400:
    $ref: './frontend/paths/err-examples.yaml#/paths/~1example~1errors~1400'
  /example/errors/401:
    $ref: './frontend/paths/err-examples.yaml#/paths/~1example~1errors~1401'
  /example/errors/403:
    $ref: './frontend/paths/err-examples.yaml#/paths/~1example~1errors~1403'
  /example/errors/404:
    $ref: './frontend/paths/err-examples.yaml#/paths/~1example~1errors~1404'