openapi: 3.0.3
info:
  title: Registry Sources 
  version: 0.1.0
components:
  parameters:
    artifact_id:
      name: artifact_id
      in: path
      required: true
      description: The unique identifier of the artifact
      schema:
        type: string
    dockerhub_integration_id:
      name: dockerhub_integration_id
      in: path
      required: true
      description: The unique identifier of the dockerhub integration
      schema:
        type: string
    gar_integration_id:
      name: gar_integration_id
      in: path
      required: true
      description: The unique identifier of the google artifact registry integration
      schema:
        type: string
    registry_source_id:
      name: registry_source_id
      in: path
      required: true
      description: The unique identifier of the registry source
      schema:
        type: string
    repository_id:
      name: repository_id
      in: path
      required: true
      description: The unique identifier of the repository
      schema:
        type: string
    workspace_id:
      name: workspace_id 
      in: path
      required: true
      description: The unique identifier of the workspace
      schema:
        type: string
paths: {}