openapi: 3.1.0
info:
  title: Miru Webhooks
  version: 0.0.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
webhooks:
  deployment.validate:
    post:
      tags:
        - Deployments
      summary: Validate
      description: Deployments requires custom validation to be performed
      operationId: validateDeployment
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ValidateDeploymentEvent'
      responses:
        '200':
          description: Successfully received the event.
components:
  schemas:
    Event:
      type: object
      required:
        - object
        - timestamp
      properties:
        object:
          type: string
          enum:
            - event
          description: The object that occurred
          example: event
        timestamp:
          type: string
          format: date-time
          description: The timestamp of the event
          example: '2021-01-01T00:00:00Z'
    WebhookDeployment:
      title: Webhook Deployment
      type: object
      required:
        - object
        - id
        - device_id
        - release_id
        - created_at
      properties:
        object:
          type: string
          enum:
            - deployment
          example: deployment
        id:
          type: string
          example: dpl_123
          description: ID of the deployment
        device_id:
          type: string
          example: dvc_123
          description: ID of the device
        release_id:
          type: string
          example: rls_123
          description: The version of the release
        created_at:
          type: string
          format: date-time
          example: '2024-01-01T00:00:00Z'
          description: Timestamp of when the device release was created
    ValidateDeploymentEvent:
      allOf:
        - $ref: '#/components/schemas/Event'
        - type: object
          required:
            - type
            - data
          properties:
            type:
              type: string
              description: The type of event
              enum:
                - deployment.validate
              example: deployment.validate
            data:
              type: object
              description: The data associated with the event
              required:
                - deployment
              properties:
                deployment:
                  $ref: '#/components/schemas/WebhookDeployment'
