openapi: 3.1.0
info:
  title: Miru Webhooks
  version: 0.1.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
webhooks:
  config_instance.target_status.validated:
    post:
      tags:
        - Config Instances
      summary: Target Status Validated
      description: The config instance is waiting for validation before deployment to a device
      operationId: configInstanceTargetStatusValidated
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConfigInstanceTargetStatusValidatedRequest'
      responses:
        '200':
          description: Successfully received the event.
components:
  schemas:
    ConfigInstanceTargetStatus:
      type: string
      description: |
        Desired state of the config instance
        - Created: config instance desires not to be deployed but can be deployed in the future
        - Validated: config instance desires user's custom validation before deployment can begin
        - Deployed: config instance desires to be available on the device
        - Removed: config instance desires to no longer be available on the device
      enum:
        - created
        - validated
        - deployed
        - removed
      x-enum-varnames:
        - CONFIG_INSTANCE_TARGET_STATUS_CREATED
        - CONFIG_INSTANCE_TARGET_STATUS_VALIDATED
        - CONFIG_INSTANCE_TARGET_STATUS_DEPLOYED
        - CONFIG_INSTANCE_TARGET_STATUS_REMOVED
    ConfigInstanceActivityStatus:
      type: string
      description: |
        Last known activity state of the config instance
        - Created: config instance has been created but no deployment attempt has been made
        - Validating: config instance is being validated with user's custom validation
        - Validated: config instance has been validated with user's custom validation
        - Queued: config instance will be deployed as soon as the device is back online
        - Deployed: config instance is currently available on the device
        - Removed: the config instance is no longer available on the device
      enum:
        - created
        - validating
        - validated
        - queued
        - deployed
        - removed
      x-enum-varnames:
        - CONFIG_INSTANCE_ACTIVITY_STATUS_CREATED
        - CONFIG_INSTANCE_ACTIVITY_STATUS_VALIDATING
        - CONFIG_INSTANCE_ACTIVITY_STATUS_VALIDATED
        - CONFIG_INSTANCE_ACTIVITY_STATUS_QUEUED
        - CONFIG_INSTANCE_ACTIVITY_STATUS_DEPLOYED
        - CONFIG_INSTANCE_ACTIVITY_STATUS_REMOVED
    ConfigInstanceErrorStatus:
      type: string
      description: |
        Last known error state of the config instance deployment
        - None: there are no errors with the config instance deployment
        - Retrying: an error has been encountered and the agent is attempting to try again to reach the target status
        - Failed: an error has been encountered but no more retries are left; the config instance is removed (if deployed)
      enum:
        - none
        - failed
        - retrying
      x-enum-varnames:
        - CONFIG_INSTANCE_ERROR_STATUS_NONE
        - CONFIG_INSTANCE_ERROR_STATUS_FAILED
        - CONFIG_INSTANCE_ERROR_STATUS_RETRYING
    ConfigInstanceStatus:
      type: string
      description: |
        This status merges the 'activity_status' and 'error_status' fields, with error states taking precedence over activity states when errors are present. For example, if the activity status is 'deployed' but there's an error, the overall status will be 'failed' or 'retrying' depending on the error state.
      enum:
        - created
        - validating
        - validated
        - queued
        - deployed
        - removed
        - failed
        - retrying
      x-enum-varnames:
        - CONFIG_INSTANCE_STATUS_CREATED
        - CONFIG_INSTANCE_STATUS_VALIDATING
        - CONFIG_INSTANCE_STATUS_VALIDATED
        - CONFIG_INSTANCE_STATUS_QUEUED
        - CONFIG_INSTANCE_STATUS_DEPLOYED
        - CONFIG_INSTANCE_STATUS_REMOVED
        - CONFIG_INSTANCE_STATUS_FAILED
        - CONFIG_INSTANCE_STATUS_RETRYING
    BaseConfigInstance:
      title: Base Config Instance
      type: object
      required:
        - object
        - id
        - target_status
        - activity_status
        - error_status
        - status
        - relative_filepath
        - created_at
        - updated_at
        - device_id
        - config_schema_id
        - config_type_id
      properties:
        object:
          type: string
          enum:
            - config_instance
          example: config_instance
        id:
          type: string
          example: cfg_inst_123
          description: ID of the config instance
        target_status:
          $ref: '#/components/schemas/ConfigInstanceTargetStatus'
        activity_status:
          $ref: '#/components/schemas/ConfigInstanceActivityStatus'
        error_status:
          $ref: '#/components/schemas/ConfigInstanceErrorStatus'
        status:
          $ref: '#/components/schemas/ConfigInstanceStatus'
        relative_filepath:
          type: string
          example: /v1/motion-control.json
          description: The file path to deploy the config instance relative to `/srv/miru/config_instances`. `v1/motion-control.json` would deploy to `/srv/miru/config_instances/v1/motion-control.json`
        created_at:
          type: string
          format: date-time
          example: '2021-01-01T00:00:00Z'
          description: The timestamp of when the config instance was created
        updated_at:
          type: string
          format: date-time
          example: '2021-01-01T00:00:00Z'
          description: The timestamp of when the config instance was last updated
        device_id:
          type: string
          example: dvc_123
          description: ID of the device which the config instance is deployed to
        config_schema_id:
          type: string
          example: cfg_sch_123
          description: ID of the config schema which the config instance must adhere to
        config_type_id:
          type: string
          example: cfg_type_123
          description: ID of the config type which the config instance (and its schema) is a part of
    ConfigInstanceTargetStatusValidatedRequest:
      type: object
      required:
        - config_instance
      properties:
        config_instance:
          $ref: '#/components/schemas/BaseConfigInstance'
