openapi: 3.0.3
info:
  title: Artifacts
  version: ""
components:
  schemas:
    DuplicateArtifact:
      title: DuplicateArtifactError
      type: object
      required:
        - code
        - params
        - message
      properties:
        code:
          type: string
          example: "duplicate_artifact"
        params:
          type: object
          required:
            - duplicate_artifacts
          properties:
            duplicate_artifacts:
              type: array
              items:
                type: object
                example: "art_1234"
        message:
          type: string
          example: "Artifacts with identical content already exist"
        debug_message:
          type: string
          example: "2 artifacts with identical content already exist: art_1234, art_5678"
paths: {}
