openapi: 3.0.3
info:
  title: Artifacts
  version: ""
components:
  schemas:
    Error: 
      title: Error
      type: object
      required:
        - error
      properties:
        error:
          type: object

    UnauthorizedError:
      title: Unauthorized
      type: object
      required:
        - code
        - params
        - message
      properties:
        code:
          type: string
          example: "invalid_clerk_auth"
        params:
          type: object
        message:
          type: string
          example: "Invalid Clerk authentication credentials"
        
    ForbiddenError:
      title: Forbidden
      type: object
      required:
        - code
        - params
        - message
      properties:
        code:
          type: string
          example: "forbidden"
        params:
          type: object
          required:
            - identity_id
            - identity_type 
            - permission
            - resource_id
            - resource_type
            - fix
          properties:
            identity_id:
              type: string
              example: "<identity_id>"
            identity_type:
              type: string
              example: "<identity_type>"
            permission:
              type: string
              example: "<permission>"
            resource_id:
              type: string
              example: "<resource_id>"
            resource_type:
              type: string
              example: "<resource_type>"
            fix:
              type: string
              example: "<fix>"
        message:
          type: string
          example: "<identity_type> '<identity_id>' does not have '<permission>' permission for <resource_type> '<resource_id>'"

    RecordNotFoundError:
      title: Record Not Found
      type: object
      required:
        - code
        - params
        - message
      properties:
        code:
          type: string
          example: "record_not_found"
        params:
          type: object
          properties:
            record_id:
              type: string
              example: "<record_id>"
            record_type:
              type: string
              example: "<record_type>"
        message:
          type: string
          example: "<record_type> '<record_id>' not found"
paths: {}
